logging:
    level:
        org.hibernate.SQL: debug

spring:
    #DB Connection
    datasource:
        driver-class-name: org.mariadb.jdbc.Driver
        url: jdbc:mariadb://localhost:3308/kotlin_board
        username: root
        password: 1234

    #JPA
    jpa:
        hibernate:
            ddl-auto: create
        show-sql: true
        properties:
            hibernate:
                format_sql: true

